version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=(link unavailable)
      - FLASK_ENV=production
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
